version: '3.8'

services:
  auth:
    build: 
      context: ./Auth
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  mynetwork:
