version: '3.8'

services:
  auth:
    build: 
      context: ./Auth
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - mynetwork
    depends_on:
    - db
    - redis

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis-data:/data
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_DB=auth_db
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres_data:

networks:
  mynetwork:
